#*****************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Tcl script for generating Vivado project
#
# Generated by Vivado on Thu Mar 07 15:18:36 CET 2024
# IP Build 4028589 on Sat Oct 14 00:45:43 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set script_file [info script]
set origin_dir [file dirname [file normalize "$script_file/../../"]]


# Set the project name
set _xil_proj_name_ "RVSoC"


# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}


if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Import Digilent boards
source $origin_dir/scripts/Vivado/import_digilent_boards.tcl

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ${origin_dir}/scripts/Vivado/project -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]


# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:genesys2:part0:1.1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "mimas_a7_50t" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "1" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "1" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "1" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "1" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]

source $origin_dir/hardware/include/cva6/corev_apu/fpga/scripts/add_sources.tcl

# prevent double-adding Northcape
set ariane_northcape_files [get_files $origin_dir/hardware/include/cva6/corev_apu/northcape/*]
remove_files $ariane_northcape_files

# will use optimized version instead
remove_files [get_files $origin_dir/hardware/include/northcape/cva6_mmu/northcape_cva6_64_bit_adder.sv]

add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/ariane"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/common"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/include"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/axis_demux"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/axis_mux"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/capability_cache"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/capability_ops"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/cva6_mmu"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/capability_resolver"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/tests/coverage/axi5_functional_coverage.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/mmu"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/xilinx"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/northcape/malicious_peripherals"]

add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/corev_apu/fpga/src/bootrom/bootrom_64.mem"]

# prevent using dummy MMU
set mmu_dummy_files [get_files $origin_dir/hardware/include/northcape/cva6_mmu/northcape_cva6_mmu_dummy.sv]
remove_files $mmu_dummy_files

# prevent using ASIC "BRAM"
set asic_bram [get_files $origin_dir/hardware/include/northcape/common/northcape_sram_dport_asic.sv]
remove_files $asic_bram

add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/corev_apu/fpga/src/genesysii.svh"]

set file_obj [get_files -of_objects $obj [list "genesysii.svh" "vendor/pulp-platform/common_cells/include/common_cells/registers.svh"]]
set_property -dict { file_type {Verilog Header} is_global_include 1} -objects $file_obj

set file_obj [get_files -of_objects $obj *trng.vhd]
set_property file_type {VHDL 2008} $file_obj

# need to be added explicitly for using CVA6 in BD
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/corev_apu/register_interface/include/register_interface/typedef.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/corev_apu/register_interface/include/register_interface/assign.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/vendor/pulp-platform/common_cells/include/common_cells/registers.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/core/include/rvfi_types.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/core/cache_subsystem/hpdcache/rtl/include/hpdcache_typedef.svh"]
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/corev_apu/tb/common/assign.svh"]

# for the axi cut module
add_files -fileset $obj -norecurse [file normalize "$origin_dir/hardware/include/cva6/vendor/pulp-platform/common_cells/src/spill_register_flushable.sv"]
add_files -fileset $obj -norecurse [file normalize "$origin_dir/hardware/include/cva6/vendor/pulp-platform/common_cells/src/spill_register.sv"]
add_files -fileset $obj -norecurse [file normalize "$origin_dir/hardware/include/cva6/vendor/pulp-platform/axi/src/axi_cut.sv"]
add_files -fileset $obj -norecurse [file normalize " $origin_dir/hardware/include/cva6/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv"]
add_files -fileset $obj -norecurse [file normalize " $origin_dir/hardware/include/cva6/vendor/pulp-platform/axi/include/axi/typedef.svh"]
add_files -fileset $obj -norecurse [file normalize " $origin_dir/hardware/include/cva6/vendor/pulp-platform/axi/include/axi/assign.svh"]

add_files -fileset $obj -scan_for_includes -verbose [file normalize "$origin_dir/hardware/hdl/ariane_wrappers"]
add_files -fileset $obj -scan_for_includes -verbose [file normalize "$origin_dir/hardware/hdl/block_design_wrappers"]
add_files -fileset $obj -scan_for_includes -verbose [file normalize "$origin_dir/hardware/hdl/tb"]
add_files -fileset $obj -scan_for_includes -verbose [file normalize "$origin_dir/hardware/hdl/northcape_wrappers"]
add_files -fileset $obj -scan_for_includes -verbose [file normalize "$origin_dir/hardware/hdl/util"]

set_property include_dirs [list \
	"$origin_dir/hardware/include/cva6/vendor/pulp-platform/common_cells/include" \
	"$origin_dir/hardware/include/cva6/vendor/pulp-platform/axi/include" \
	"$origin_dir/hardware/include/cva6/core/cache_subsystem/hpdcache/rtl/include" \
	"$origin_dir/hardware/include/cva6/corev_apu/register_interface/include" \
	"$origin_dir/hardware/include/cva6/core/include" \
  "$origin_dir/hardware/include/cva6/corev_apu/tb/common" \
  "$origin_dir/hardware/include/northcape/ariane" \
  "$origin_dir/hardware/include/northcape/mmu" \
  "$origin_dir/hardware/include/northcape/common" \
  "$origin_dir/hardware/include/northcape/xilinx" \
  "$origin_dir/hardware/hdl/ariane_wrappers" \
 ] $obj

set_property file_type "Verilog Header" [get_files "$origin_dir/hardware/include/northcape/common/northcape_unread.vh"]

add_files -fileset $obj -verbose [list \
  [file normalize "$origin_dir/hardware/include/analogdevices-hdl-lib/library/common/up_axi.v"]\
  [file normalize "$origin_dir/hardware/include/analogdevices-hdl-lib/library/common/util_pulse_gen.v"]\
  [file normalize "$origin_dir/hardware/include/analogdevices-hdl-lib/library/axi_fan_control/axi_fan_control.v"]\
]

add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/include/cva6/core/include/cv64a6_imafdc_sv39_northcape_config_pkg.sv"]

puts "Sourcing ha1588"
source "$origin_dir/hardware/include/northcape-ha1588/par/xilinx/ha1588_import_sources.tcl"

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "SoC_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
add_files -fileset $obj [file normalize "$origin_dir/hardware/constraints/Genesys-2-Master.xdc"]
set file "Genesys-2-Master.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name used_in_synthesis -value false -objects $file_obj

# Add/Import constrs file and set constrs file properties
add_files -fileset $obj -verbose [file normalize "$origin_dir/hardware/constraints/project_constraints.xdc"]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*project_constraints.xdc"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property used_in_synthesis false $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files [list "*project_constraints.xdc"]]" -objects $obj
set_property -name "target_ucf" -value "[get_files [list "*project_constraints.xdc"]]" -objects $obj

source $origin_dir/scripts/Vivado/import_digilent_pmods.tcl
# IP might be used in block design modules, so create it first
source $origin_dir/scripts/Vivado/create_ip.tcl
source $origin_dir/scripts/Vivado/create_bd.tcl

make_wrapper -files [get_files *SoC.bd] -top
add_files -norecurse "$origin_dir/scripts/Vivado/project/RVSoC.gen/sources_1/bd/SoC/hdl/SoC_wrapper.v"
set_property top SoC_wrapper [current_fileset]

update_compile_order -fileset sources_1

add_files -fileset sim_1 -scan_for_includes [list                         \
  [file normalize "$origin_dir/hardware/hdl/tb/wiredly.v"]                \
  [file normalize "$origin_dir/hardware/hdl/tb/ddr3_model.sv"]            \
  [file normalize "$origin_dir/hardware/hdl/tb/vivado_top.sv"]            \
  [file normalize "$origin_dir/hardware/hdl/tb/ddr3_model_parameters.vh"] \
]

set_property top vivado_top [get_fileset sim_1]


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2023} -strategy "Flow_AlternateRoutability" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Flow_AlternateRoutability" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}

set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj

set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Flow_AlternateRoutability" -objects $obj

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2024} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2024" [get_runs impl_1]
}
set obj [get_runs impl_1]

# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
# TODO bus skew reports get stuck currently
set_property report_strategy {Vivado Implementation Default Reports} -objects $obj
delete_report_configs [get_report_configs -of_objects $obj impl_1_route_report_bus_skew_0] 
set_property -name "steps.init_design.tcl.post" -value "[file normalize "$origin_dir/hardware/constraints/fix_tx_ctl.tcl"]" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj


# try a little harder to close timing
set_property STEPS.OPT_DESIGN.ARGS.DIRECTIVE Explore [get_runs impl_1]
set_property STEPS.PLACE_DESIGN.ARGS.DIRECTIVE ExtraTimingOpt [get_runs impl_1]
set_property STEPS.POST_PLACE_POWER_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.ARGS.DIRECTIVE AggressiveExplore [get_runs impl_1]
set_property STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE MoreGlobalIterations [get_runs impl_1]
set_property -name {STEPS.ROUTE_DESIGN.ARGS.MORE OPTIONS} -value -tns_cleanup -objects [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.ARGS.DIRECTIVE AggressiveExplore [get_runs impl_1]

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1

# error in synthesis if we assign to an output
set_msg_config  -id {Synth 8-6104 }  -new_severity {ERROR}  -ruleid {1}  -source 2
# error in synthesis for undeclared signal
set_msg_config  -id {Synth 8-11241}  -new_severity {CRITICAL WARNING}  -ruleid {2}  -source 2
# spurious warning about clocking being ignored
set_msg_config  -id {Synth 8-6155}  -new_severity {INFO}
set_msg_config  -id {Synth 8-2898}  -new_severity {INFO}
