#ifndef SKADI_ASM_H
#define SKADI_ASM_H
/* skadi-specific assembler routines */
#include <zephyr/toolchain.h>
#include <zephyr/sys/util_macro.h>

#define SKADI_SCALL_OPCODE 0b1100111
#define SKADI_SCALL_OPCODE_FUNC3 0x1
#define SKADI_SCALLS_OPCODE_FUNC3 0x2

#define SKADI_SCALL_ID_OPCODE 0b0001011
#define SKADI_SCALL_ID_FUNC3  0x0
#define SKADI_SCALL_ID_FUNC7  0x0

#define SKADI_ZREGS_OPCODE 0b0110011
#define SKADI_ZREGS_FUNC3  0x00
#define SKADI_ZREGS_FUNC7  0x21

/* GP register set */
#define SKADI_CLEAR_REG_ZERO    BIT(0)
#define SKADI_CLEAR_REG_RA      BIT(1)
#define SKADI_CLEAR_REG_SP      BIT(2)
#define SKADI_CLEAR_REG_GP      BIT(3)
#define SKADI_CLEAR_REG_TP      BIT(4)
#define SKADI_CLEAR_REG_T0      BIT(5)
#define SKADI_CLEAR_REG_T1      BIT(6)
#define SKADI_CLEAR_REG_T2      BIT(7)
#define SKADI_CLEAR_REG_S0      BIT(8)
#define SKADI_CLEAR_REG_S1      BIT(9)
#define SKADI_CLEAR_REG_A0      BIT(10)
#define SKADI_CLEAR_REG_A1      BIT(11)
#define SKADI_CLEAR_REG_A2      BIT(12)
#define SKADI_CLEAR_REG_A3      BIT(13)
#define SKADI_CLEAR_REG_A4      BIT(14)
#define SKADI_CLEAR_REG_A5      BIT(15)
#define SKADI_CLEAR_REG_A6      BIT(16)
#define SKADI_CLEAR_REG_A7      BIT(17)
#define SKADI_CLEAR_REG_S2      BIT(18)
#define SKADI_CLEAR_REG_S3      BIT(19)
#define SKADI_CLEAR_REG_S4      BIT(20)
#define SKADI_CLEAR_REG_S5      BIT(21)
#define SKADI_CLEAR_REG_S6      BIT(22)
#define SKADI_CLEAR_REG_S7      BIT(23)
#define SKADI_CLEAR_REG_S8      BIT(24)
#define SKADI_CLEAR_REG_S9      BIT(25)
#define SKADI_CLEAR_REG_S10     BIT(26)
#define SKADI_CLEAR_REG_S11     BIT(27)
#define SKADI_CLEAR_REG_T3      BIT(28)
#define SKADI_CLEAR_REG_T4      BIT(29)
#define SKADI_CLEAR_REG_T5      BIT(30)
#define SKADI_CLEAR_REG_T6      BIT(31)

#define SKADI_CLEAR_REG_FT0     BIT(32)
#define SKADI_CLEAR_REG_FT1     BIT(33)
#define SKADI_CLEAR_REG_FT2     BIT(34)
#define SKADI_CLEAR_REG_FT3     BIT(35)
#define SKADI_CLEAR_REG_FT4     BIT(36)
#define SKADI_CLEAR_REG_FT5     BIT(37)
#define SKADI_CLEAR_REG_FT6     BIT(38)
#define SKADI_CLEAR_REG_FT7     BIT(39)
#define SKADI_CLEAR_REG_FS0     BIT(40)
#define SKADI_CLEAR_REG_FS1     BIT(41)
#define SKADI_CLEAR_REG_FA0     BIT(42)
#define SKADI_CLEAR_REG_FA1     BIT(43)
#define SKADI_CLEAR_REG_FA2     BIT(44)
#define SKADI_CLEAR_REG_FA3     BIT(45)
#define SKADI_CLEAR_REG_FA4     BIT(46)
#define SKADI_CLEAR_REG_FA5     BIT(47)
#define SKADI_CLEAR_REG_FA6     BIT(48)
#define SKADI_CLEAR_REG_FA7     BIT(49)
#define SKADI_CLEAR_REG_FS2     BIT(50)
#define SKADI_CLEAR_REG_FS3     BIT(51)
#define SKADI_CLEAR_REG_FS4     BIT(52)
#define SKADI_CLEAR_REG_FS5     BIT(53)
#define SKADI_CLEAR_REG_FS6     BIT(54)
#define SKADI_CLEAR_REG_FS7     BIT(55)
#define SKADI_CLEAR_REG_FS8     BIT(56)
#define SKADI_CLEAR_REG_FS9     BIT(57)
#define SKADI_CLEAR_REG_FS10    BIT(58)
#define SKADI_CLEAR_REG_FS11    BIT(59)
#define SKADI_CLEAR_REG_FT8     BIT(60)
#define SKADI_CLEAR_REG_FT9     BIT(61)
#define SKADI_CLEAR_REG_FT10    BIT(62)
#define SKADI_CLEAR_REG_FT11    BIT(63)

/* on return, need return address for jump, integer return (a0) and float return (fa0) */
#define SKADI_CLEAR_REG_CALLEE ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0)

/* calls: need to let argument registers (if any), return address, register with callee trampoline (t1) alive; also, SP, GP handled separately */
#define SKADI_CLEAR_REG_CALLER_0_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1)
#define SKADI_CLEAR_REG_CALLER_1_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0)
#define SKADI_CLEAR_REG_CALLER_2_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1)
#define SKADI_CLEAR_REG_CALLER_3_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2)
#define SKADI_CLEAR_REG_CALLER_4_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2 & ~SKADI_CLEAR_REG_A3 & ~SKADI_CLEAR_REG_FA3)
#define SKADI_CLEAR_REG_CALLER_5_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2 & ~SKADI_CLEAR_REG_A3 & ~SKADI_CLEAR_REG_FA3 & ~SKADI_CLEAR_REG_A4 & ~SKADI_CLEAR_REG_FA4)
#define SKADI_CLEAR_REG_CALLER_6_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2 & ~SKADI_CLEAR_REG_A3 & ~SKADI_CLEAR_REG_FA3 & ~SKADI_CLEAR_REG_A4 & ~SKADI_CLEAR_REG_FA4 & ~SKADI_CLEAR_REG_A5 & ~SKADI_CLEAR_REG_FA5)
#define SKADI_CLEAR_REG_CALLER_7_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2 & ~SKADI_CLEAR_REG_A3 & ~SKADI_CLEAR_REG_FA3 & ~SKADI_CLEAR_REG_A4 & ~SKADI_CLEAR_REG_FA4 & ~SKADI_CLEAR_REG_A5 & ~SKADI_CLEAR_REG_FA5 & ~SKADI_CLEAR_REG_A6 & ~SKADI_CLEAR_REG_FA6)
#define SKADI_CLEAR_REG_CALLER_8_ARGS ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_SP & ~SKADI_CLEAR_REG_GP & ~SKADI_CLEAR_REG_T1 & ~SKADI_CLEAR_REG_A0 & ~SKADI_CLEAR_REG_FA0 & ~SKADI_CLEAR_REG_A1 & ~SKADI_CLEAR_REG_FA1 & ~SKADI_CLEAR_REG_A2 & ~SKADI_CLEAR_REG_FA2 & ~SKADI_CLEAR_REG_A3 & ~SKADI_CLEAR_REG_FA3 & ~SKADI_CLEAR_REG_A4 & ~SKADI_CLEAR_REG_FA4 & ~SKADI_CLEAR_REG_A5 & ~SKADI_CLEAR_REG_FA5 & ~SKADI_CLEAR_REG_A6 & ~SKADI_CLEAR_REG_FA6 & ~SKADI_CLEAR_REG_A7 & ~SKADI_CLEAR_REG_FA7)

/* CANNOT use the normal SKADI_CLEAR_REG_CALLER_0_ARGS macro here, as the caller stub uses t0 to jump! */
#define SKADI_CLEAR_REG_YIELD_STUB    ((0xffffffffffffffffUL) & ~SKADI_CLEAR_REG_RA & ~SKADI_CLEAR_REG_T0)

#define SKADI_REGCALL(MASK_REG) .insn r SKADI_ZREGS_OPCODE, SKADI_ZREGS_FUNC3, SKADI_ZREGS_FUNC7, zero, MASK_REG, zero
#define SKADI_REGCALL_STR(MASK_REG) ".insn r " STRINGIFY(SKADI_ZREGS_OPCODE) "," STRINGIFY(SKADI_ZREGS_FUNC3) "," STRINGIFY(SKADI_ZREGS_FUNC7) ", zero, " STRINGIFY(MASK_REG) ", zero"

#define SKADI_SCALL(REG,IMM) .insn i SKADI_SCALL_OPCODE, SKADI_SCALL_OPCODE_FUNC3, zero, REG, IMM

#define SKADI_SCALL_STR(REG,IMM) ".insn i " STRINGIFY(SKADI_SCALL_OPCODE) "," STRINGIFY(SKADI_SCALL_OPCODE_FUNC3) ", zero," STRINGIFY(REG) "," STRINGIFY(IMM)

#define SKADI_SCALLS(REG,IMM) .insn i SKADI_SCALL_OPCODE, SKADI_SCALLS_OPCODE_FUNC3, zero, REG, IMM
#define SKADI_SCALLS_STR(REG,IMM) ".insn i " STRINGIFY(SKADI_SCALL_OPCODE) "," STRINGIFY(SKADI_SCALLS_OPCODE_FUNC3) ", zero," STRINGIFY(REG) "," STRINGIFY(IMM)

/* R type: rs1 holds the target, rs2 holds the task ID */
#define SKADI_SCALL_ID(TARGET_REG,ID_REG) .insn r SKADI_SCALL_ID_OPCODE, SKADI_SCALL_ID_FUNC3, SKADI_SCALL_ID_FUNC7, zero, TARGET_REG, ID_REG
#define SKADI_SCALL_ID_STR(TARGET_REG,ID_REG) ".insn r " STRINGIFY(SKADI_SCALL_ID_OPCODE) "," STRINGIFY(SKADI_SCALL_ID_FUNC3) ", " STRINGIFY(SKADI_SCALL_ID_FUNC7) ", zero," STRINGIFY(TARGET_REG) "," STRINGIFY(ID_REG)

#define SKADI_SRET SKADI_SCALL(ra, 0)
#define SKADI_SRET_STR SKADI_SCALL_STR(ra, 0)
#define SKADI_SRETS SKADI_SCALLS(ra, 0)
#define SKADI_SRETS_STR SKADI_SCALLS_STR(ra, 0)

#endif
