# unneeded subsystems
CONFIG_NETWORKING=n
CONFIG_DMA=n
CONFIG_PULP_APB_TIMER=n

# size optimization
CONFIG_SKADI_SUBSYSTEM_STACK_SIZE=1023
CONFIG_SKADI_SUBSYSTEM_CALLER_TRAMPOLINE_NUM_REGISTER_SETS=4
CONFIG_SKADI_SUBSYSTEM_CALLEE_TRAMPOLINE_NUM_STACKS=4
CONFIG_SKADI_ISR_STACK_SIZE=1024
CONFIG_SKADI_DEBUG_MODULE_DRIVER=n
CONFIG_SKADI_LIBC_INLINE=n
CONFIG_SKADI_TEXT_ALIGN_12_BIT=n
CONFIG_SKADI_LIBRARY_LOCAL_ALLOCATOR=n
CONFIG_SKADI_LIBRARY_LOCAL_CLOCK=n
CONFIG_SKADI_EARLYCON=n
CONFIG_SKADI_SUBSYS_SYNC_ATOMIC=y
