#!/bin/sh

set -e

echo "Exporting Hardware Platform for Vitis"
cd ../Vivado
if [ -z "${IS_GENESYS}" ]; then
    /opt/Xilinx/Vivado/2024.2/bin/vivado -mode batch -source create_xsa_arty.tcl
else
    if [ -z "${IS_NORTHERN_LIGHTS}" ]; then
        /opt/Xilinx/Vivado/2024.2/bin/vivado -mode batch -source create_xsa.tcl
    else
        /opt/Xilinx/Vivado/2024.2/bin/vivado -mode batch -source create_xsa_northern_lights.tcl
    fi
fi
cd ../Vitis

if [ -d device-tree-xlnx ];
then 
    echo "Xilinx Device Tree Repo exists";
else
    echo "Cloning Xilinx Device Tree Repo!";
    git clone https://github.com/Xilinx/device-tree-xlnx --depth 1 -b xilinx_v2023.2
fi

echo "Preparing vitis working directory"
rm -r vitis_tmp 2>&1 >/dev/null || true
mkdir vitis_tmp 2>&1 >/dev/null

if [ -z "${IS_GENESYS}" ]; then
    cp ../Vivado/project_arty/SoC_wrapper.xsa vitis_tmp
else
    if [ -z "${IS_NORTHERN_LIGHTS}" ]; then
        cp ../Vivado/project/SoC_wrapper.xsa vitis_tmp
    else
        cp ../Vivado/project_northern_lights/SoC_wrapper.xsa vitis_tmp
    fi
fi

cd vitis_tmp

echo "Modifying Hardware handover files"
unzip SoC_wrapper.xsa

rm SoC_wrapper.xsa


if [ -z "${IS_GENESYS}" ]; then
    
    # same thing, but different name of the wrapper
    sed -i 's;<MODULE COREREVISION="1" FULLNAME="/ariane_peripherals/axi_riscv_atomics_wr_0" HWVERSION="1.0" INSTANCE="ariane_peripherals_axi_riscv_atomics_wr_0" IPTYPE="PERIPHERAL" IS_ENABLE="1" MODCLASS="PERIPHERAL" MODTYPE="axi_riscv_atomics_wrapper_verilog_arty" VLNV="xilinx.com:module_ref:axi_riscv_atomics_wrapper_verilog_arty:1.0">;<MODULE COREREVISION="1" FULLNAME="/ariane_peripherals/axi_riscv_atomics_wr_0" HWVERSION="1.0" INSTANCE="ariane_peripherals_axi_riscv_atomics_wr_0" IPTYPE="PROCESSOR" IS_ENABLE="1" MODCLASS="PROCESSOR" MODTYPE="microblaze" PROCTYPE="microblaze" VLNV="xilinx.com:ip:microblaze:11.0">;g' SoC.hwh

    sed -i 's;<PARAMETER NAME="Component_Name" VALUE="SoC_axi_riscv_atomics_wr_0_0"/>;\
<PARAMETER NAME="Component_Name" VALUE="SoC_axi_riscv_atomics_wr_0_0"/>\
<PARAMETER NAME="C_ADDR_TAG_BITS" VALUE="0"/>\
<PARAMETER NAME="C_ALLOW_DCACHE_WR" VALUE="1"/>\
<PARAMETER NAME="C_ALLOW_ICACHE_WR" VALUE="1"/>\
<PARAMETER NAME="C_AREA_OPTIMIZED" VALUE="1"/>\
<PARAMETER NAME="C_ASYNC_INTERRUPT" VALUE="1"/>\
<PARAMETER NAME="C_ASYNC_WAKEUP" VALUE="3"/>\
<PARAMETER NAME="C_AVOID_PRIMITIVES" VALUE="0"/>\
<PARAMETER NAME="C_BASE_VECTORS" VALUE="0x0000000000000000"/>\
<PARAMETER NAME="C_BRANCH_TARGET_CACHE_SIZE" VALUE="0"/>\
<PARAMETER NAME="C_CACHE_BYTE_SIZE" VALUE="8192"/>\
<PARAMETER NAME="C_DADDR_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_DATA_SIZE" VALUE="64"/>\
<PARAMETER NAME="C_DCACHE_ADDR_TAG" VALUE="0"/>\
<PARAMETER NAME="C_DCACHE_ALWAYS_USED" VALUE="1"/>\
<PARAMETER NAME="C_DCACHE_BASEADDR" VALUE="0x0000000000000000"/>\
<PARAMETER NAME="C_DCACHE_BYTE_SIZE" VALUE="8192"/>\
<PARAMETER NAME="C_DCACHE_DATA_WIDTH" VALUE="0"/>\
<PARAMETER NAME="C_DCACHE_FORCE_TAG_LUTRAM" VALUE="0"/>\
<PARAMETER NAME="C_DCACHE_HIGHADDR" VALUE="0x000000003fffffff"/>\
<PARAMETER NAME="C_DCACHE_LINE_LEN" VALUE="4"/>\
<PARAMETER NAME="C_DCACHE_USE_WRITEBACK" VALUE="0"/>\
<PARAMETER NAME="C_DCACHE_VICTIMS" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_COUNTER_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_DEBUG_ENABLED" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_EVENT_COUNTERS" VALUE="5"/>\
<PARAMETER NAME="C_DEBUG_EXTERNAL_TRACE" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_INTERFACE" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_LATENCY_COUNTERS" VALUE="1"/>\
<PARAMETER NAME="C_DEBUG_PROFILE_SIZE" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_TRACE_ASYNC_RESET" VALUE="0"/>\
<PARAMETER NAME="C_DEBUG_TRACE_SIZE" VALUE="8192"/>\
<PARAMETER NAME="C_DIV_ZERO_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_DYNAMIC_BUS_SIZING" VALUE="0"/>\
<PARAMETER NAME="C_D_AXI" VALUE="1"/>\
<PARAMETER NAME="C_D_LMB" VALUE="1"/>\
<PARAMETER NAME="C_D_LMB_PROTOCOL" VALUE="0"/>\
<PARAMETER NAME="C_ECC_USE_CE_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_EDGE_IS_POSITIVE" VALUE="1"/>\
<PARAMETER NAME="C_FAMILY" VALUE="kintex7"/>\
<PARAMETER NAME="C_FAULT_TOLERANT" VALUE="0"/>\
<PARAMETER NAME="C_FPU_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_FREQ" VALUE="50000000"/>\
<PARAMETER NAME="C_FSL_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_FSL_LINKS" VALUE="0"/>\
<PARAMETER NAME="C_IADDR_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_ICACHE_ALWAYS_USED" VALUE="1"/>\
<PARAMETER NAME="C_ICACHE_BASEADDR" VALUE="0x0000000000000000"/>\
<PARAMETER NAME="C_ICACHE_DATA_WIDTH" VALUE="0"/>\
<PARAMETER NAME="C_ICACHE_FORCE_TAG_LUTRAM" VALUE="0"/>\
<PARAMETER NAME="C_ICACHE_HIGHADDR" VALUE="0x000000003fffffff"/>\
<PARAMETER NAME="C_ICACHE_LINE_LEN" VALUE="4"/>\
<PARAMETER NAME="C_ICACHE_STREAMS" VALUE="0"/>\
<PARAMETER NAME="C_ICACHE_VICTIMS" VALUE="0"/>\
<PARAMETER NAME="C_ILL_OPCODE_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_IMPRECISE_EXCEPTIONS" VALUE="0"/>\
<PARAMETER NAME="C_INSTANCE" VALUE="SoC_microblaze_0_0"/>\
<PARAMETER NAME="C_INSTR_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_INTERCONNECT" VALUE="2"/>\
<PARAMETER NAME="C_INTERRUPT_IS_EDGE" VALUE="0"/>\
<PARAMETER NAME="C_I_AXI" VALUE="1"/>\
<PARAMETER NAME="C_I_LMB" VALUE="1"/>\
<PARAMETER NAME="C_I_LMB_PROTOCOL" VALUE="0"/>\
<PARAMETER NAME="C_LMB_DATA_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_LOCKSTEP_MASTER" VALUE="0"/>\
<PARAMETER NAME="C_LOCKSTEP_SLAVE" VALUE="0"/>\
<PARAMETER NAME="C_M0_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M10_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M11_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M12_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M13_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M14_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M15_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M1_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M2_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M3_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M4_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M5_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M6_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M7_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M8_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M9_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_MMU_DTLB_SIZE" VALUE="4"/>\
<PARAMETER NAME="C_MMU_ITLB_SIZE" VALUE="2"/>\
<PARAMETER NAME="C_MMU_PRIVILEGED_INSTR" VALUE="0"/>\
<PARAMETER NAME="C_MMU_TLB_ACCESS" VALUE="3"/>\
<PARAMETER NAME="C_MMU_ZONES" VALUE="16"/>\
<PARAMETER NAME="C_M_AXI_DC_ADDR_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_DC_ARUSER_WIDTH" VALUE="5"/>\
<PARAMETER NAME="C_M_AXI_DC_AWUSER_WIDTH" VALUE="5"/>\
<PARAMETER NAME="C_M_AXI_DC_BUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_DC_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_DC_EXCLUSIVE_ACCESS" VALUE="0"/>\
<PARAMETER NAME="C_M_AXI_DC_RUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_DC_THREAD_ID_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_DC_USER_VALUE" VALUE="31"/>\
<PARAMETER NAME="C_M_AXI_DC_WUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_DP_ADDR_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_DP_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_DP_EXCLUSIVE_ACCESS" VALUE="0"/>\
<PARAMETER NAME="C_M_AXI_DP_THREAD_ID_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_D_BUS_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_M_AXI_IC_ADDR_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_IC_ARUSER_WIDTH" VALUE="5"/>\
<PARAMETER NAME="C_M_AXI_IC_AWUSER_WIDTH" VALUE="5"/>\
<PARAMETER NAME="C_M_AXI_IC_BUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_IC_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_IC_RUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_IC_THREAD_ID_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_IC_USER_VALUE" VALUE="31"/>\
<PARAMETER NAME="C_M_AXI_IC_WUSER_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_IP_ADDR_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_IP_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_M_AXI_IP_THREAD_ID_WIDTH" VALUE="1"/>\
<PARAMETER NAME="C_M_AXI_I_BUS_EXCEPTION" VALUE="0"/>\
<PARAMETER NAME="C_NUMBER_OF_PC_BRK" VALUE="1"/>\
<PARAMETER NAME="C_NUMBER_OF_RD_ADDR_BRK" VALUE="0"/>\
<PARAMETER NAME="C_NUMBER_OF_WR_ADDR_BRK" VALUE="0"/>\
<PARAMETER NAME="C_NUM_SYNC_FF_CLK" VALUE="2"/>\
<PARAMETER NAME="C_NUM_SYNC_FF_CLK_DEBUG" VALUE="2"/>\
<PARAMETER NAME="C_NUM_SYNC_FF_CLK_IRQ" VALUE="1"/>\
<PARAMETER NAME="C_NUM_SYNC_FF_DBG_CLK" VALUE="1"/>\
<PARAMETER NAME="C_NUM_SYNC_FF_DBG_TRACE_CLK" VALUE="2"/>\
<PARAMETER NAME="C_OPCODE_0x0_ILLEGAL" VALUE="0"/>\
<PARAMETER NAME="C_OPTIMIZATION" VALUE="0"/>\
<PARAMETER NAME="C_PART" VALUE="xc7k325tffg900-2"/>\
<PARAMETER NAME="C_PC_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_PIADDR_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_PVR" VALUE="0"/>\
<PARAMETER NAME="C_PVR_USER1" VALUE="0x00"/>\
<PARAMETER NAME="C_PVR_USER2" VALUE="0x00000000"/>\
<PARAMETER NAME="C_RESET_MSR" VALUE="0x00000000"/>\
<PARAMETER NAME="C_S0_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S10_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S11_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S12_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S13_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S14_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S15_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S1_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S2_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S3_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S4_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S5_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S6_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S7_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S8_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_S9_AXIS_DATA_WIDTH" VALUE="32"/>\
<PARAMETER NAME="C_SCO" VALUE="0"/>\
<PARAMETER NAME="C_TEMPORAL_DEPTH" VALUE="0"/>\
<PARAMETER NAME="C_UNALIGNED_EXCEPTIONS" VALUE="0"/>\
<PARAMETER NAME="C_USE_BARREL" VALUE="0"/>\
<PARAMETER NAME="C_USE_BRANCH_TARGET_CACHE" VALUE="0"/>\
<PARAMETER NAME="C_USE_CONFIG_RESET" VALUE="0"/>\
<PARAMETER NAME="C_USE_DCACHE" VALUE="0"/>\
<PARAMETER NAME="C_USE_DIV" VALUE="0"/>\
<PARAMETER NAME="C_USE_EXTENDED_FSL_INSTR" VALUE="0"/>\
<PARAMETER NAME="C_USE_EXT_BRK" VALUE="0"/>\
<PARAMETER NAME="C_USE_EXT_NM_BRK" VALUE="0"/>\
<PARAMETER NAME="C_USE_FPU" VALUE="0"/>\
<PARAMETER NAME="C_USE_HW_MUL" VALUE="0"/>\
<PARAMETER NAME="C_USE_ICACHE" VALUE="0"/>\
<PARAMETER NAME="C_USE_INTERRUPT" VALUE="0"/>\
<PARAMETER NAME="C_USE_MMU" VALUE="0"/>\
<PARAMETER NAME="C_USE_MSR_INSTR" VALUE="0"/>\
<PARAMETER NAME="C_USE_NON_SECURE" VALUE="0"/>\
<PARAMETER NAME="C_USE_PCMP_INSTR" VALUE="0"/>\
<PARAMETER NAME="C_USE_REORDER_INSTR" VALUE="1"/>\
<PARAMETER NAME="C_USE_STACK_PROTECTION" VALUE="0"/>\
<PARAMETER NAME="G_TEMPLATE_LIST" VALUE="0"/>\
<PARAMETER NAME="C_ADDR_SIZE" VALUE="32"/>\
<PARAMETER NAME="C_DC_AXI_MON" VALUE="0"/>\
<PARAMETER NAME="C_DP_AXI_MON" VALUE="0"/>\
<PARAMETER NAME="C_D_LMB_MON" VALUE="0"/>\
<PARAMETER NAME="C_ENABLE_DISCRETE_PORTS" VALUE="0"/>\
<PARAMETER NAME="C_IC_AXI_MON" VALUE="0"/>\
<PARAMETER NAME="C_INTERRUPT_MON" VALUE="0"/>\
<PARAMETER NAME="C_IP_AXI_MON" VALUE="0"/>\
<PARAMETER NAME="C_I_LMB_MON" VALUE="0"/>\
<PARAMETER NAME="C_LOCKSTEP_SELECT" VALUE="0"/>\
<PARAMETER NAME="C_M0_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M10_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M11_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M12_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M13_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M14_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M15_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M1_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M2_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M3_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M4_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M5_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M6_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M7_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M8_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M9_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_M_AXI_DC_USER_SIGNALS" VALUE="0"/>\
<PARAMETER NAME="C_M_AXI_IC_USER_SIGNALS" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_BIP" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_DCE" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_EE" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_EIP" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_ICE" VALUE="0"/>\
<PARAMETER NAME="C_RESET_MSR_IE" VALUE="0"/>\
<PARAMETER NAME="C_S0_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S10_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S11_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S12_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S13_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S14_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S15_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S1_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S2_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S3_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S4_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S5_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S6_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S7_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S8_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_S9_AXIS_PROTOCOL" VALUE="GENERIC"/>\
<PARAMETER NAME="C_TRACE" VALUE="0"/>\
<PARAMETER NAME="Component_Name" VALUE="SoC_microblaze_0_0"/>\
<PARAMETER NAME="G_USE_EXCEPTIONS" VALUE="0"/>\
<PARAMETER NAME="C_ENDIANNESS" VALUE="1"/>\
<PARAMETER NAME="EDK_IPTYPE" VALUE="PROCESSOR"/>\
<PARAMETER NAME="EDK_SPECIAL" VALUE="microblaze"/>;' SoC.hwh
else
# for Vitis to generate the device tree, we must have a Softcore CPU - we pretend that Northcape is actually a Microblaze
    sed -i 's;<MODULE COREREVISION="1" FULLNAME="/northcape_northbridge/northcape_caps/axi_riscv_atomics_wrapper_0" HWVERSION="1.0" INSTANCE="northcape_northbridge_northcape_caps_axi_riscv_atomics_wrapper_0" IPTYPE="PERIPHERAL" IS_ENABLE="1" MODCLASS="PERIPHERAL" MODTYPE="axi_riscv_atomics_wrapper_verilog" VLNV="xilinx.com:module_ref:axi_riscv_atomics_wrapper_verilog:1.0">;<MODULE COREREVISION="1" FULLNAME="/northcape_northbridge/northcape_caps/axi_riscv_atomics_wrapper" HWVERSION="11.0" INSTANCE="northcape_northbridge_northcape_caps_axi_riscv_atomics_wrapper" IPTYPE="PROCESSOR" IS_ENABLE="1" MODCLASS="PROCESSOR" MODTYPE="microblaze" PROCTYPE="microblaze" VLNV="xilinx.com:ip:microblaze:11.0">;g' SoC.hwh
    sed -i 's;<PARAMETER NAME="Component_Name" VALUE="SoC_axi_riscv_atomics_wrapper_0_0"/>;\
    <PARAMETER NAME="Component_Name" VALUE="SoC_axi_riscv_atomics_wrapper_0_0"/>\
    <PARAMETER NAME="C_ADDR_TAG_BITS" VALUE="0"/>\
    <PARAMETER NAME="C_ALLOW_DCACHE_WR" VALUE="1"/>\
    <PARAMETER NAME="C_ALLOW_ICACHE_WR" VALUE="1"/>\
    <PARAMETER NAME="C_AREA_OPTIMIZED" VALUE="1"/>\
    <PARAMETER NAME="C_ASYNC_INTERRUPT" VALUE="1"/>\
    <PARAMETER NAME="C_ASYNC_WAKEUP" VALUE="3"/>\
    <PARAMETER NAME="C_AVOID_PRIMITIVES" VALUE="0"/>\
    <PARAMETER NAME="C_BASE_VECTORS" VALUE="0x0000000000000000"/>\
    <PARAMETER NAME="C_BRANCH_TARGET_CACHE_SIZE" VALUE="0"/>\
    <PARAMETER NAME="C_CACHE_BYTE_SIZE" VALUE="8192"/>\
    <PARAMETER NAME="C_DADDR_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_DATA_SIZE" VALUE="64"/>\
    <PARAMETER NAME="C_DCACHE_ADDR_TAG" VALUE="0"/>\
    <PARAMETER NAME="C_DCACHE_ALWAYS_USED" VALUE="1"/>\
    <PARAMETER NAME="C_DCACHE_BASEADDR" VALUE="0x0000000000000000"/>\
    <PARAMETER NAME="C_DCACHE_BYTE_SIZE" VALUE="8192"/>\
    <PARAMETER NAME="C_DCACHE_DATA_WIDTH" VALUE="0"/>\
    <PARAMETER NAME="C_DCACHE_FORCE_TAG_LUTRAM" VALUE="0"/>\
    <PARAMETER NAME="C_DCACHE_HIGHADDR" VALUE="0x000000003fffffff"/>\
    <PARAMETER NAME="C_DCACHE_LINE_LEN" VALUE="4"/>\
    <PARAMETER NAME="C_DCACHE_USE_WRITEBACK" VALUE="0"/>\
    <PARAMETER NAME="C_DCACHE_VICTIMS" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_COUNTER_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_DEBUG_ENABLED" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_EVENT_COUNTERS" VALUE="5"/>\
    <PARAMETER NAME="C_DEBUG_EXTERNAL_TRACE" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_INTERFACE" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_LATENCY_COUNTERS" VALUE="1"/>\
    <PARAMETER NAME="C_DEBUG_PROFILE_SIZE" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_TRACE_ASYNC_RESET" VALUE="0"/>\
    <PARAMETER NAME="C_DEBUG_TRACE_SIZE" VALUE="8192"/>\
    <PARAMETER NAME="C_DIV_ZERO_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_DYNAMIC_BUS_SIZING" VALUE="0"/>\
    <PARAMETER NAME="C_D_AXI" VALUE="1"/>\
    <PARAMETER NAME="C_D_LMB" VALUE="1"/>\
    <PARAMETER NAME="C_D_LMB_PROTOCOL" VALUE="0"/>\
    <PARAMETER NAME="C_ECC_USE_CE_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_EDGE_IS_POSITIVE" VALUE="1"/>\
    <PARAMETER NAME="C_FAMILY" VALUE="kintex7"/>\
    <PARAMETER NAME="C_FAULT_TOLERANT" VALUE="0"/>\
    <PARAMETER NAME="C_FPU_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_FREQ" VALUE="50000000"/>\
    <PARAMETER NAME="C_FSL_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_FSL_LINKS" VALUE="0"/>\
    <PARAMETER NAME="C_IADDR_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_ICACHE_ALWAYS_USED" VALUE="1"/>\
    <PARAMETER NAME="C_ICACHE_BASEADDR" VALUE="0x0000000000000000"/>\
    <PARAMETER NAME="C_ICACHE_DATA_WIDTH" VALUE="0"/>\
    <PARAMETER NAME="C_ICACHE_FORCE_TAG_LUTRAM" VALUE="0"/>\
    <PARAMETER NAME="C_ICACHE_HIGHADDR" VALUE="0x000000003fffffff"/>\
    <PARAMETER NAME="C_ICACHE_LINE_LEN" VALUE="4"/>\
    <PARAMETER NAME="C_ICACHE_STREAMS" VALUE="0"/>\
    <PARAMETER NAME="C_ICACHE_VICTIMS" VALUE="0"/>\
    <PARAMETER NAME="C_ILL_OPCODE_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_IMPRECISE_EXCEPTIONS" VALUE="0"/>\
    <PARAMETER NAME="C_INSTANCE" VALUE="SoC_microblaze_0_0"/>\
    <PARAMETER NAME="C_INSTR_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_INTERCONNECT" VALUE="2"/>\
    <PARAMETER NAME="C_INTERRUPT_IS_EDGE" VALUE="0"/>\
    <PARAMETER NAME="C_I_AXI" VALUE="1"/>\
    <PARAMETER NAME="C_I_LMB" VALUE="1"/>\
    <PARAMETER NAME="C_I_LMB_PROTOCOL" VALUE="0"/>\
    <PARAMETER NAME="C_LMB_DATA_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_LOCKSTEP_MASTER" VALUE="0"/>\
    <PARAMETER NAME="C_LOCKSTEP_SLAVE" VALUE="0"/>\
    <PARAMETER NAME="C_M0_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M10_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M11_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M12_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M13_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M14_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M15_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M1_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M2_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M3_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M4_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M5_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M6_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M7_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M8_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M9_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_MMU_DTLB_SIZE" VALUE="4"/>\
    <PARAMETER NAME="C_MMU_ITLB_SIZE" VALUE="2"/>\
    <PARAMETER NAME="C_MMU_PRIVILEGED_INSTR" VALUE="0"/>\
    <PARAMETER NAME="C_MMU_TLB_ACCESS" VALUE="3"/>\
    <PARAMETER NAME="C_MMU_ZONES" VALUE="16"/>\
    <PARAMETER NAME="C_M_AXI_DC_ADDR_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_DC_ARUSER_WIDTH" VALUE="5"/>\
    <PARAMETER NAME="C_M_AXI_DC_AWUSER_WIDTH" VALUE="5"/>\
    <PARAMETER NAME="C_M_AXI_DC_BUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_DC_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_DC_EXCLUSIVE_ACCESS" VALUE="0"/>\
    <PARAMETER NAME="C_M_AXI_DC_RUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_DC_THREAD_ID_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_DC_USER_VALUE" VALUE="31"/>\
    <PARAMETER NAME="C_M_AXI_DC_WUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_DP_ADDR_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_DP_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_DP_EXCLUSIVE_ACCESS" VALUE="0"/>\
    <PARAMETER NAME="C_M_AXI_DP_THREAD_ID_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_D_BUS_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_M_AXI_IC_ADDR_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_IC_ARUSER_WIDTH" VALUE="5"/>\
    <PARAMETER NAME="C_M_AXI_IC_AWUSER_WIDTH" VALUE="5"/>\
    <PARAMETER NAME="C_M_AXI_IC_BUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_IC_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_IC_RUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_IC_THREAD_ID_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_IC_USER_VALUE" VALUE="31"/>\
    <PARAMETER NAME="C_M_AXI_IC_WUSER_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_IP_ADDR_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_IP_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_M_AXI_IP_THREAD_ID_WIDTH" VALUE="1"/>\
    <PARAMETER NAME="C_M_AXI_I_BUS_EXCEPTION" VALUE="0"/>\
    <PARAMETER NAME="C_NUMBER_OF_PC_BRK" VALUE="1"/>\
    <PARAMETER NAME="C_NUMBER_OF_RD_ADDR_BRK" VALUE="0"/>\
    <PARAMETER NAME="C_NUMBER_OF_WR_ADDR_BRK" VALUE="0"/>\
    <PARAMETER NAME="C_NUM_SYNC_FF_CLK" VALUE="2"/>\
    <PARAMETER NAME="C_NUM_SYNC_FF_CLK_DEBUG" VALUE="2"/>\
    <PARAMETER NAME="C_NUM_SYNC_FF_CLK_IRQ" VALUE="1"/>\
    <PARAMETER NAME="C_NUM_SYNC_FF_DBG_CLK" VALUE="1"/>\
    <PARAMETER NAME="C_NUM_SYNC_FF_DBG_TRACE_CLK" VALUE="2"/>\
    <PARAMETER NAME="C_OPCODE_0x0_ILLEGAL" VALUE="0"/>\
    <PARAMETER NAME="C_OPTIMIZATION" VALUE="0"/>\
    <PARAMETER NAME="C_PART" VALUE="xc7k325tffg900-2"/>\
    <PARAMETER NAME="C_PC_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_PIADDR_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_PVR" VALUE="0"/>\
    <PARAMETER NAME="C_PVR_USER1" VALUE="0x00"/>\
    <PARAMETER NAME="C_PVR_USER2" VALUE="0x00000000"/>\
    <PARAMETER NAME="C_RESET_MSR" VALUE="0x00000000"/>\
    <PARAMETER NAME="C_S0_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S10_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S11_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S12_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S13_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S14_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S15_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S1_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S2_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S3_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S4_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S5_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S6_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S7_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S8_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_S9_AXIS_DATA_WIDTH" VALUE="32"/>\
    <PARAMETER NAME="C_SCO" VALUE="0"/>\
    <PARAMETER NAME="C_TEMPORAL_DEPTH" VALUE="0"/>\
    <PARAMETER NAME="C_UNALIGNED_EXCEPTIONS" VALUE="0"/>\
    <PARAMETER NAME="C_USE_BARREL" VALUE="0"/>\
    <PARAMETER NAME="C_USE_BRANCH_TARGET_CACHE" VALUE="0"/>\
    <PARAMETER NAME="C_USE_CONFIG_RESET" VALUE="0"/>\
    <PARAMETER NAME="C_USE_DCACHE" VALUE="0"/>\
    <PARAMETER NAME="C_USE_DIV" VALUE="0"/>\
    <PARAMETER NAME="C_USE_EXTENDED_FSL_INSTR" VALUE="0"/>\
    <PARAMETER NAME="C_USE_EXT_BRK" VALUE="0"/>\
    <PARAMETER NAME="C_USE_EXT_NM_BRK" VALUE="0"/>\
    <PARAMETER NAME="C_USE_FPU" VALUE="0"/>\
    <PARAMETER NAME="C_USE_HW_MUL" VALUE="0"/>\
    <PARAMETER NAME="C_USE_ICACHE" VALUE="0"/>\
    <PARAMETER NAME="C_USE_INTERRUPT" VALUE="0"/>\
    <PARAMETER NAME="C_USE_MMU" VALUE="0"/>\
    <PARAMETER NAME="C_USE_MSR_INSTR" VALUE="0"/>\
    <PARAMETER NAME="C_USE_NON_SECURE" VALUE="0"/>\
    <PARAMETER NAME="C_USE_PCMP_INSTR" VALUE="0"/>\
    <PARAMETER NAME="C_USE_REORDER_INSTR" VALUE="1"/>\
    <PARAMETER NAME="C_USE_STACK_PROTECTION" VALUE="0"/>\
    <PARAMETER NAME="G_TEMPLATE_LIST" VALUE="0"/>\
    <PARAMETER NAME="C_ADDR_SIZE" VALUE="32"/>\
    <PARAMETER NAME="C_DC_AXI_MON" VALUE="0"/>\
    <PARAMETER NAME="C_DP_AXI_MON" VALUE="0"/>\
    <PARAMETER NAME="C_D_LMB_MON" VALUE="0"/>\
    <PARAMETER NAME="C_ENABLE_DISCRETE_PORTS" VALUE="0"/>\
    <PARAMETER NAME="C_IC_AXI_MON" VALUE="0"/>\
    <PARAMETER NAME="C_INTERRUPT_MON" VALUE="0"/>\
    <PARAMETER NAME="C_IP_AXI_MON" VALUE="0"/>\
    <PARAMETER NAME="C_I_LMB_MON" VALUE="0"/>\
    <PARAMETER NAME="C_LOCKSTEP_SELECT" VALUE="0"/>\
    <PARAMETER NAME="C_M0_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M10_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M11_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M12_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M13_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M14_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M15_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M1_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M2_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M3_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M4_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M5_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M6_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M7_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M8_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M9_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_M_AXI_DC_USER_SIGNALS" VALUE="0"/>\
    <PARAMETER NAME="C_M_AXI_IC_USER_SIGNALS" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_BIP" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_DCE" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_EE" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_EIP" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_ICE" VALUE="0"/>\
    <PARAMETER NAME="C_RESET_MSR_IE" VALUE="0"/>\
    <PARAMETER NAME="C_S0_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S10_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S11_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S12_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S13_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S14_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S15_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S1_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S2_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S3_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S4_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S5_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S6_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S7_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S8_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_S9_AXIS_PROTOCOL" VALUE="GENERIC"/>\
    <PARAMETER NAME="C_TRACE" VALUE="0"/>\
    <PARAMETER NAME="Component_Name" VALUE="SoC_microblaze_0_0"/>\
    <PARAMETER NAME="G_USE_EXCEPTIONS" VALUE="0"/>\
    <PARAMETER NAME="C_ENDIANNESS" VALUE="1"/>\
    <PARAMETER NAME="EDK_IPTYPE" VALUE="PROCESSOR"/>\
    <PARAMETER NAME="EDK_SPECIAL" VALUE="microblaze"/>;' SoC.hwh

    sed -i '/<PARAMETER NAME="EDK_IPTYPE" VALUE="PROCESSOR"\/>/,/PROCESSOR/ s/<PARAMETER NAME="EDK_IPTYPE" VALUE="PERIPHERAL"\/>//' SoC.hwh
fi

sed -i '/<PARAMETER NAME="EDK_IPTYPE" VALUE="PROCESSOR"\/>/,/PROCESSOR/ s/<PARAMETER NAME="EDK_IPTYPE" VALUE="PERIPHERAL"\/>//' SoC.hwh


zip SoC_wrapper.xsa *

cd ..

echo "Running Vitis to create device tree"
/opt/Xilinx/Vitis/2024.2/bin/xsct create_dt.tcl

echo "Generating device tree include file for cva6"
sed -i 's|#include|/include/|g' vitis_tmp/device_tree/system-top.dts

if [ -z "${IS_GENESYS}" ]; then
    echo "Assuming ARTY"
    dtc -I dts modified_system_top_arty.dts -O dtb -o vitis_tmp/northcape.dtb
else
    if [ -z "${IS_NORTHERN_LIGHTS}" ]; then
        dtc -I dts modified_system_top.dts -O dtb -o vitis_tmp/northcape.dtb
    else
        dtc -I dts modified_system_top_northern_lights.dts -O dtb -o vitis_tmp/northcape.dtb
    fi
fi

dtc -I dtb vitis_tmp/northcape.dtb -O dts -o vitis_tmp/northcape.dts

cp vitis_tmp/northcape.dts ../../hardware/include/cva6/corev_apu/fpga/src/bootrom/northcape.dtsi

echo "Generating Zero-Stage Bootloader with updated device tree"
cd ../../hardware/include/cva6/corev_apu/fpga/src/bootrom

make clean

if [ -z "${IS_GENESYS}" ]; then
    echo "Assuming ARTY"
    HAS_NORTHCAPE=1 UART_BITRATE=115200 BOARD=arty_a7_100 make
else
    echo "Assuming Genesys"
    HAS_NORTHCAPE=1 HAS_ETHERNET=1 make
fi

cd ../../../..

echo "Re-generating Vivado source file for Bootloader"
HAS_NORTHCAPE=1 HAS_ETHERNET=1 make fpga-source-list src/bootrom/bootrom_64.sv || exit 1
