# Test sources in Verilog
${NORTHCAPE_ROOT}/common/northcape_unread.sv
${NORTHCAPE_ROOT}/common/axis5.sv
${NORTHCAPE_ROOT}/common/axi5.sv
${NORTHCAPE_ROOT}/common/spi.sv
${NORTHCAPE_ROOT}/common/northcape_types.sv
${NORTHCAPE_ROOT}/common/northcape_sram_sport.sv
${NORTHCAPE_ROOT}/common/northcape_sram_dport.sv
${NORTHCAPE_ROOT}/common/northcape_sram_dport_wenable.sv
${NORTHCAPE_ROOT}/common/northcape_sram_dport_wenable_indclock.sv
${NORTHCAPE_ROOT}/common/shift_reg_lowarea.sv
${NORTHCAPE_ROOT}/common/twoff_sync.sv
${NORTHCAPE_ROOT}/common/northcape_fifo.sv
${NORTHCAPE_ROOT}/common/northcape_sram_initializer.sv
${NORTHCAPE_ROOT}/common/northcape_cmt_parser.sv
${NORTHCAPE_ROOT}/common/northcape_rng.sv
${NORTHCAPE_ROOT}/include/verilog_qarma/qarma_64.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_sbox.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_inv_sbox.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_key_mem.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_encipher_block.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_decipher_block.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes_core.v
${NORTHCAPE_ROOT}/include/aes/src/rtl/aes.v
${NORTHCAPE_ROOT}/include/sha256/src/rtl/sha256_k_constants.v
${NORTHCAPE_ROOT}/include/sha256/src/rtl/sha256_w_mem.v
${NORTHCAPE_ROOT}/include/sha256/src/rtl/sha256_core.v
${NORTHCAPE_ROOT}/include/sha256/src/rtl/sha256.v
${NORTHCAPE_ROOT}/common/qarmaCBCMac.sv
${NORTHCAPE_ROOT}/common/northcape_user_parser.sv
${NORTHCAPE_ROOT}/common/axis5_pipeline_stage.sv
${NORTHCAPE_ROOT}/common/axis5_fifo_skidbuffer.sv
${NORTHCAPE_ROOT}/common/northcape_leading_zero_count.sv
${NORTHCAPE_ROOT}/axis_mux/axis5_mux.sv
${NORTHCAPE_ROOT}/axis_demux/axis5_demux.sv
${NORTHCAPE_ROOT}/mmu/northcape_mmu_common.sv
${NORTHCAPE_ROOT}/mmu/northcape_mmu_read_chan.sv
${NORTHCAPE_ROOT}/mmu/northcape_mmu_write_chan.sv
${NORTHCAPE_ROOT}/mmu/northcape_mmu.sv
${NORTHCAPE_ROOT}/malicious_peripherals/northcape_confused_deputy_dma.sv
${NORTHCAPE_ROOT}/common/northcape_reg_interface.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_common.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver_common.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops_common.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_arbiter.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_store_buffer.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_missunit.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_writeback_unit.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_wt_direct_ff.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_wt_fully_assoc_ff.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_wt_direct_bram.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache_wt_n_assoc_bram.sv
${NORTHCAPE_ROOT}/capability_cache/northcape_capability_cache.sv
${NORTHCAPE_ROOT}/cva6_mmu/northcape_cva6_mmu_cache.sv
${NORTHCAPE_ROOT}/cva6_mmu/northcape_cva6_mmu.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver_hash.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver_lookup.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver_cache_interface.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver_parser.sv
${NORTHCAPE_ROOT}/capability_resolver/northcape_capability_resolver.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops_create_cap.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops_zero_cmt.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops_zero_main_mem_segment.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops_trng_reg.sv
${NORTHCAPE_ROOT}/capability_ops/northcape_capability_ops.sv
${NORTHCAPE_ROOT}/tests/generator/northcape_generator.sv
${NORTHCAPE_ROOT}/tests/test_data_structures.sv
${NORTHCAPE_ROOT}/tests/checker/northcape_generic_checker.sv
${NORTHCAPE_ROOT}/tests/sequence/northcape_sequence.sv
${NORTHCAPE_ROOT}/tests/reset/northcape_reset_agent.sv
${NORTHCAPE_ROOT}/tests/env/northcape_generic_env.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_sparse_mem_simulator.sv
${NORTHCAPE_ROOT}/tests/drivers/axi5_mem_adapter.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_capability_cache_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_bram_driver.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_transaction.sv
${NORTHCAPE_ROOT}/tests/drivers/axi5_lite_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/axis5_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_rng_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_reg_interface_driver.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_intf.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_cva6_mmu_intf_driver.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_sequence.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_csr_interface.sv
${NORTHCAPE_ROOT}/tests/drivers/axi5_slave_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/axi5_master_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_axis_validate_driver.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_test_trng.sv
${NORTHCAPE_ROOT}/tests/clock/northcape_test_clock_generator.sv
${NORTHCAPE_ROOT}/tests/drivers/northcape_capability_ops_csr_interface_driver.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_transaction.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_sequence.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_scoreboard.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/fifo/northcape_fifo_agent.sv
${NORTHCAPE_ROOT}/tests/uvm_wrapper/northcape_uvm_test_discovery.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_test_constants.sv
${NORTHCAPE_ROOT}/tests/component_specific/fifo/northcape_fifo_test_constants.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_test_constants.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_transaction.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_agent.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_unit_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_unit_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_unit_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_unit_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_unit_test.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_unit_test.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/fifo/northcape_fifo_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_randomized_test.sv
${NORTHCAPE_ROOT}/tests/component_specific/mmu/northcape_mmu_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/cva6_mmu/northcape_cva6_mmu_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/confused_deputy_dma/northcape_confused_deputy_dma_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_resolver/northcape_capability_resolver_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_cache/northcape_capability_cache_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/capability_ops/northcape_capability_ops_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/reg_interface/northcape_reg_interface_top.sv
${NORTHCAPE_ROOT}/tests/component_specific/fifo/northcape_fifo_top.sv
${NORTHCAPE_ROOT}/tests/integration/northcape_integration_top.sv
--include ${NORTHCAPE_ROOT}/mmu/
--include ${NORTHCAPE_ROOT}/common/
--include ${NORTHCAPE_ROOT}/capability_resolver/
--include ${NORTHCAPE_ROOT}/capability_ops/
--include ${NORTHCAPE_ROOT}/ariane/
--include ${NORTHCAPE_ROOT}/xilinx/
--include ${NORTHCAPE_ROOT}/tests/coverage/
--include ${NORTHCAPE_ROOT}/tests/uvm_wrapper/
