`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 11/04/2025 07:18:52 PM
// Design Name: 
// Module Name: openflow_switch_verilog
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module openflow_switch_verilog#(
    parameter C_NUM_INPUTS=5,
    parameter C_DATA_WIDTH=256,
    parameter C_PACKET_LENGTH_WIDTH=14,
    parameter C_TKEEP_WIDTH=32,
    parameter C_IN_PORT_WIDTH=3,
    parameter C_OUT_PORT_WIDTH=8,
    parameter C_TIMESLICE_WIDTH=9,
    parameter C_TIMESLICE_0=280,
    parameter C_TIMESLICE_1=280,
    parameter C_TIMESLICE_2=280,
    parameter C_TIMESLICE_3=280,
    parameter C_TIMESLICE_4=280,
    parameter C_TIMESLICE_5=280,
    parameter C_TIMESLICE_6=280,
    parameter C_TIMESLICE_7=280
)(
    input wire clk,
    input wire reset,
    
    // 4 Ethernet ports + 1 DMA
    input  wire [C_DATA_WIDTH-1:0] s_axis_tdata_0,
    input  wire [C_TKEEP_WIDTH-1:0] s_axis_tkeep_0,
    input  wire s_axis_tlast_0,
    input  wire s_axis_tvalid_0,
    input  wire [C_PACKET_LENGTH_WIDTH-1:0] s_axis_tuser_packet_length_0,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_port_0,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_port_0,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_vport_0,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_vport_0,
    output wire  s_axis_tready_0,
    
    input  wire [C_DATA_WIDTH-1:0] s_axis_tdata_1,
    input  wire [C_TKEEP_WIDTH-1:0] s_axis_tkeep_1,
    input  wire s_axis_tlast_1,
    input  wire s_axis_tvalid_1,
    input  wire [C_PACKET_LENGTH_WIDTH-1:0] s_axis_tuser_packet_length_1,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_port_1,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_port_1,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_vport_1,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_vport_1,
    output wire  s_axis_tready_1,
    
    input  wire [C_DATA_WIDTH-1:0] s_axis_tdata_2,
    input  wire [C_TKEEP_WIDTH-1:0] s_axis_tkeep_2,
    input  wire s_axis_tlast_2,
    input  wire s_axis_tvalid_2,
    input  wire [C_PACKET_LENGTH_WIDTH-1:0] s_axis_tuser_packet_length_2,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_port_2,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_port_2,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_vport_2,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_vport_2,
    output wire  s_axis_tready_2,
    
    input  wire [C_DATA_WIDTH-1:0] s_axis_tdata_3,
    input  wire [C_TKEEP_WIDTH-1:0] s_axis_tkeep_3,
    input  wire s_axis_tlast_3,
    input  wire s_axis_tvalid_3,
    input  wire [C_PACKET_LENGTH_WIDTH-1:0] s_axis_tuser_packet_length_3,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_port_3,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_port_3,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_vport_3,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_vport_3,
    output wire  s_axis_tready_3,
    
    input  wire [C_DATA_WIDTH-1:0] s_axis_tdata_4,
    input  wire [C_TKEEP_WIDTH-1:0] s_axis_tkeep_4,
    input  wire s_axis_tlast_4,
    input  wire s_axis_tvalid_4,
    input  wire [C_PACKET_LENGTH_WIDTH-1:0] s_axis_tuser_packet_length_4,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_port_4,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_port_4,
    input  wire [C_IN_PORT_WIDTH-1:0] s_axis_tuser_in_vport_4,
    input  wire [C_OUT_PORT_WIDTH-1:0] s_axis_tuser_out_vport_4,
    output wire  s_axis_tready_4,

    // AXI-Lite interfaces of the Switch
    input  wire s_axi_stats_awvalid,
    output wire s_axi_stats_awready,
    input  wire [31:0] s_axi_stats_awaddr,
    input  wire [2:0] s_axi_stats_awprot,
    input  wire s_axi_stats_wvalid,
    output wire  s_axi_stats_wready,
    input  wire [31:0] s_axi_stats_wdata,
    input  wire [3:0] s_axi_stats_wstrb,
    output wire  s_axi_stats_bvalid,
    input  wire s_axi_stats_bready,
    output wire [1:0] s_axi_stats_bresp,
    input  wire s_axi_stats_arvalid,
    output wire s_axi_stats_arready,
    input  wire [31:0] s_axi_stats_araddr,
    input  wire [2:0] s_axi_stats_arprot,
    output wire s_axi_stats_rvalid,
    input  wire s_axi_stats_rready,
    output wire [31:0] s_axi_stats_rdata,
    output wire [1:0] s_axi_stats_rresp,
    
    input  wire s_axi_tcam_awvalid,
    output wire s_axi_tcam_awready,
    input  wire [31:0] s_axi_tcam_awaddr,
    input  wire [2:0] s_axi_tcam_awprot,
    input  wire s_axi_tcam_wvalid,
    output wire  s_axi_tcam_wready,
    input  wire [31:0] s_axi_tcam_wdata,
    input  wire [3:0] s_axi_tcam_wstrb,
    output wire  s_axi_tcam_bvalid,
    input  wire s_axi_tcam_bready,
    output wire [1:0] s_axi_tcam_bresp,
    input  wire s_axi_tcam_arvalid,
    output wire s_axi_tcam_arready,
    input  wire [31:0] s_axi_tcam_araddr,
    input  wire [2:0] s_axi_tcam_arprot,
    output wire s_axi_tcam_rvalid,
    input  wire s_axi_tcam_rready,
    output wire [31:0] s_axi_tcam_rdata,
    output wire [1:0] s_axi_tcam_rresp,
    
    input  wire s_axi_cam_awvalid,
    output wire s_axi_cam_awready,
    input  wire [31:0] s_axi_cam_awaddr,
    input  wire [2:0] s_axi_cam_awprot,
    input  wire s_axi_cam_wvalid,
    output wire  s_axi_cam_wready,
    input  wire [31:0] s_axi_cam_wdata,
    input  wire [3:0] s_axi_cam_wstrb,
    output wire  s_axi_cam_bvalid,
    input  wire s_axi_cam_bready,
    output wire [1:0] s_axi_cam_bresp,
    input  wire s_axi_cam_arvalid,
    output wire s_axi_cam_arready,
    input  wire [31:0] s_axi_cam_araddr,
    input  wire [2:0] s_axi_cam_arprot,
    output wire s_axi_cam_rvalid,
    input  wire s_axi_cam_rready,
    output wire [31:0] s_axi_cam_rdata,
    output wire [1:0] s_axi_cam_rresp,

    // output ports back to Ethernet
    output wire [C_DATA_WIDTH-1:0] m_axis_tdata_0,
    output wire [C_TKEEP_WIDTH-1:0] m_axis_tkeep_0,
    output wire m_axis_tlast_0,
    output wire m_axis_tvalid_0,
    output wire [C_PACKET_LENGTH_WIDTH-1:0] m_axis_tuser_packet_length_0,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_port_0,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_port_0,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_vport_0,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_vport_0,
    input wire m_axis_tready_0,

    output wire [C_DATA_WIDTH-1:0] m_axis_tdata_1,
    output wire [C_TKEEP_WIDTH-1:0] m_axis_tkeep_1,
    output wire m_axis_tlast_1,
    output wire m_axis_tvalid_1,
    output wire [C_PACKET_LENGTH_WIDTH-1:0] m_axis_tuser_packet_length_1,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_port_1,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_port_1,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_vport_1,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_vport_1,
    input wire m_axis_tready_1,

    output wire [C_DATA_WIDTH-1:0] m_axis_tdata_2,
    output wire [C_TKEEP_WIDTH-1:0] m_axis_tkeep_2,
    output wire m_axis_tlast_2,
    output wire m_axis_tvalid_2,
    output wire [C_PACKET_LENGTH_WIDTH-1:0] m_axis_tuser_packet_length_2,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_port_2,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_port_2,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_vport_2,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_vport_2,
    input wire m_axis_tready_2,

    output wire [C_DATA_WIDTH-1:0] m_axis_tdata_3,
    output wire [C_TKEEP_WIDTH-1:0] m_axis_tkeep_3,
    output wire m_axis_tlast_3,
    output wire m_axis_tvalid_3,
    output wire [C_PACKET_LENGTH_WIDTH-1:0] m_axis_tuser_packet_length_3,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_port_3,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_port_3,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_vport_3,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_vport_3,
    input wire m_axis_tready_3,

    output wire [C_DATA_WIDTH-1:0] m_axis_tdata_4,
    output wire [C_TKEEP_WIDTH-1:0] m_axis_tkeep_4,
    output wire m_axis_tlast_4,
    output wire m_axis_tvalid_4,
    output wire [C_PACKET_LENGTH_WIDTH-1:0] m_axis_tuser_packet_length_4,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_port_4,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_port_4,
    output wire [C_IN_PORT_WIDTH-1:0] m_axis_tuser_in_vport_4,
    output wire [C_OUT_PORT_WIDTH-1:0] m_axis_tuser_out_vport_4,
    input wire m_axis_tready_4
);

openflow_switch#(
    .C_NUM_INPUTS(C_NUM_INPUTS),
    .C_DATA_WIDTH(C_DATA_WIDTH),
    .C_PACKET_LENGTH_WIDTH(C_PACKET_LENGTH_WIDTH),
    .C_TKEEP_WIDTH(C_TKEEP_WIDTH),
    .C_IN_PORT_WIDTH(C_IN_PORT_WIDTH),
    .C_OUT_PORT_WIDTH(C_OUT_PORT_WIDTH),
    .C_TIMESLICE_WIDTH(C_TIMESLICE_WIDTH),
    .C_TIMESLICE_0(C_TIMESLICE_0),
    .C_TIMESLICE_1(C_TIMESLICE_1),
    .C_TIMESLICE_2(C_TIMESLICE_2),
    .C_TIMESLICE_3(C_TIMESLICE_3),
    .C_TIMESLICE_4(C_TIMESLICE_4),
    .C_TIMESLICE_5(C_TIMESLICE_5),
    .C_TIMESLICE_6(C_TIMESLICE_6),
    .C_TIMESLICE_7(C_TIMESLICE_7)
) i_openflow_switch(
    .clk(clk),
    .reset(reset),
    
    // 4 Ethernet ports + 1 DMA
    .s_axis_tdata_0(s_axis_tdata_0),
    .s_axis_tkeep_0(s_axis_tkeep_0),
    .s_axis_tlast_0(s_axis_tlast_0),
    .s_axis_tvalid_0(s_axis_tvalid_0),
    .s_axis_tuser_packet_length_0(s_axis_tuser_packet_length_0),
    .s_axis_tuser_in_port_0(s_axis_tuser_in_port_0),
    .s_axis_tuser_out_port_0(s_axis_tuser_out_port_0),
    .s_axis_tuser_in_vport_0(s_axis_tuser_in_vport_0),
    .s_axis_tuser_out_vport_0(s_axis_tuser_out_vport_0),
    .s_axis_tready_0(s_axis_tready_0),
    
    .s_axis_tdata_1(s_axis_tdata_1),
    .s_axis_tkeep_1(s_axis_tkeep_1),
    .s_axis_tlast_1(s_axis_tlast_1),
    .s_axis_tvalid_1(s_axis_tvalid_1),
    .s_axis_tuser_packet_length_1(s_axis_tuser_packet_length_1),
    .s_axis_tuser_in_port_1(s_axis_tuser_in_port_1),
    .s_axis_tuser_out_port_1(s_axis_tuser_out_port_1),
    .s_axis_tuser_in_vport_1(s_axis_tuser_in_vport_1),
    .s_axis_tuser_out_vport_1(s_axis_tuser_out_vport_1),
    .s_axis_tready_1(s_axis_tready_1),
    
    .s_axis_tdata_2(s_axis_tdata_2),
    .s_axis_tkeep_2(s_axis_tkeep_2),
    .s_axis_tlast_2(s_axis_tlast_2),
    .s_axis_tvalid_2(s_axis_tvalid_2),
    .s_axis_tuser_packet_length_2(s_axis_tuser_packet_length_2),
    .s_axis_tuser_in_port_2(s_axis_tuser_in_port_2),
    .s_axis_tuser_out_port_2(s_axis_tuser_out_port_2),
    .s_axis_tuser_in_vport_2(s_axis_tuser_in_vport_2),
    .s_axis_tuser_out_vport_2(s_axis_tuser_out_vport_2),
    .s_axis_tready_2(s_axis_tready_2),
    
    .s_axis_tdata_3(s_axis_tdata_3),
    .s_axis_tkeep_3(s_axis_tkeep_3),
    .s_axis_tlast_3(s_axis_tlast_3),
    .s_axis_tvalid_3(s_axis_tvalid_3),
    .s_axis_tuser_packet_length_3(s_axis_tuser_packet_length_3),
    .s_axis_tuser_in_port_3(s_axis_tuser_in_port_3),
    .s_axis_tuser_out_port_3(s_axis_tuser_out_port_3),
    .s_axis_tuser_in_vport_3(s_axis_tuser_in_vport_3),
    .s_axis_tuser_out_vport_3(s_axis_tuser_out_vport_3),
    .s_axis_tready_3(s_axis_tready_3),
    
    .s_axis_tdata_4(s_axis_tdata_4),
    .s_axis_tkeep_4(s_axis_tkeep_4),
    .s_axis_tlast_4(s_axis_tlast_4),
    .s_axis_tvalid_4(s_axis_tvalid_4),
    .s_axis_tuser_packet_length_4(s_axis_tuser_packet_length_4),
    .s_axis_tuser_in_port_4(s_axis_tuser_in_port_4),
    .s_axis_tuser_out_port_4(s_axis_tuser_out_port_4),
    .s_axis_tuser_in_vport_4(s_axis_tuser_in_vport_4),
    .s_axis_tuser_out_vport_4(s_axis_tuser_out_vport_4),
    .s_axis_tready_4(s_axis_tready_4),

    // AXI-Lite interfaces of the Switch
    .s_axi_stats_arvalid(s_axi_stats_arvalid),
    .s_axi_stats_araddr(s_axi_stats_araddr),
    .s_axi_stats_arprot(s_axi_stats_arprot),
    .s_axi_stats_rready(s_axi_stats_rready),
    .s_axi_stats_arready(s_axi_stats_arready), 
    .s_axi_stats_rvalid(s_axi_stats_rvalid), 
    .s_axi_stats_rdata(s_axi_stats_rdata),
    .s_axi_stats_rresp(s_axi_stats_rresp),
    
    .s_axi_tcam_awvalid(s_axi_tcam_awvalid),
    .s_axi_tcam_awready(s_axi_tcam_awready),
    .s_axi_tcam_awaddr(s_axi_tcam_awaddr),
    .s_axi_tcam_awprot(s_axi_tcam_awprot),
    .s_axi_tcam_wvalid(s_axi_tcam_wvalid),
    .s_axi_tcam_wready(s_axi_tcam_wready),
    .s_axi_tcam_wdata(s_axi_tcam_wdata),
    .s_axi_tcam_wstrb(s_axi_tcam_wstrb),
    .s_axi_tcam_bvalid(s_axi_tcam_bvalid),
    .s_axi_tcam_bready(s_axi_tcam_bready),
    .s_axi_tcam_bresp(s_axi_tcam_bresp),
    .s_axi_tcam_arvalid(s_axi_tcam_arvalid),
    .s_axi_tcam_arready(s_axi_tcam_arready),
    .s_axi_tcam_araddr(s_axi_tcam_araddr),
    .s_axi_tcam_arprot(s_axi_tcam_arprot),
    .s_axi_tcam_rvalid(s_axi_tcam_rvalid),
    .s_axi_tcam_rready(s_axi_tcam_rready),
    .s_axi_tcam_rdata(s_axi_tcam_rdata),
    .s_axi_tcam_rresp(s_axi_tcam_rresp),

    .s_axi_cam_awvalid(s_axi_cam_awvalid),
    .s_axi_cam_awready(s_axi_cam_awready),
    .s_axi_cam_awaddr(s_axi_cam_awaddr),
    .s_axi_cam_awprot(s_axi_cam_awprot),
    .s_axi_cam_wvalid(s_axi_cam_wvalid),
    .s_axi_cam_wready(s_axi_cam_wready),
    .s_axi_cam_wdata(s_axi_cam_wdata),
    .s_axi_cam_wstrb(s_axi_cam_wstrb),
    .s_axi_cam_bvalid(s_axi_cam_bvalid),
    .s_axi_cam_bready(s_axi_cam_bready),
    .s_axi_cam_bresp(s_axi_cam_bresp),
    .s_axi_cam_arvalid(s_axi_cam_arvalid),
    .s_axi_cam_arready(s_axi_cam_arready),
    .s_axi_cam_araddr(s_axi_cam_araddr),
    .s_axi_cam_arprot(s_axi_cam_arprot),
    .s_axi_cam_rvalid(s_axi_cam_rvalid),
    .s_axi_cam_rready(s_axi_cam_rready),
    .s_axi_cam_rdata(s_axi_cam_rdata),
    .s_axi_cam_rresp(s_axi_cam_rresp),

    // output ports back to Ethernet
    .m_axis_tdata_0(m_axis_tdata_0),
    .m_axis_tkeep_0(m_axis_tkeep_0),
    .m_axis_tlast_0(m_axis_tlast_0),
    .m_axis_tvalid_0(m_axis_tvalid_0),
    .m_axis_tuser_packet_length_0(m_axis_tuser_packet_length_0),
    .m_axis_tuser_in_port_0(m_axis_tuser_in_port_0),
    .m_axis_tuser_out_port_0(m_axis_tuser_out_port_0),
    .m_axis_tuser_in_vport_0(m_axis_tuser_in_vport_0),
    .m_axis_tuser_out_vport_0(m_axis_tuser_out_vport_0),
    .m_axis_tready_0(m_axis_tready_0),

    .m_axis_tdata_1(m_axis_tdata_1),
    .m_axis_tkeep_1(m_axis_tkeep_1),
    .m_axis_tlast_1(m_axis_tlast_1),
    .m_axis_tvalid_1(m_axis_tvalid_1),
    .m_axis_tuser_packet_length_1(m_axis_tuser_packet_length_1),
    .m_axis_tuser_in_port_1(m_axis_tuser_in_port_1),
    .m_axis_tuser_out_port_1(m_axis_tuser_out_port_1),
    .m_axis_tuser_in_vport_1(m_axis_tuser_in_vport_1),
    .m_axis_tuser_out_vport_1(m_axis_tuser_out_vport_1),
    .m_axis_tready_1(m_axis_tready_1),

    .m_axis_tdata_2(m_axis_tdata_2),
    .m_axis_tkeep_2(m_axis_tkeep_2),
    .m_axis_tlast_2(m_axis_tlast_2),
    .m_axis_tvalid_2(m_axis_tvalid_2),
    .m_axis_tuser_packet_length_2(m_axis_tuser_packet_length_2),
    .m_axis_tuser_in_port_2(m_axis_tuser_in_port_2),
    .m_axis_tuser_out_port_2(m_axis_tuser_out_port_2),
    .m_axis_tuser_in_vport_2(m_axis_tuser_in_vport_2),
    .m_axis_tuser_out_vport_2(m_axis_tuser_out_vport_2),
    .m_axis_tready_2(m_axis_tready_2),

    .m_axis_tdata_3(m_axis_tdata_3),
    .m_axis_tkeep_3(m_axis_tkeep_3),
    .m_axis_tlast_3(m_axis_tlast_3),
    .m_axis_tvalid_3(m_axis_tvalid_3),
    .m_axis_tuser_packet_length_3(m_axis_tuser_packet_length_3),
    .m_axis_tuser_in_port_3(m_axis_tuser_in_port_3),
    .m_axis_tuser_out_port_3(m_axis_tuser_out_port_3),
    .m_axis_tuser_in_vport_3(m_axis_tuser_in_vport_3),
    .m_axis_tuser_out_vport_3(m_axis_tuser_out_vport_3),
    .m_axis_tready_3(m_axis_tready_3),

    .m_axis_tdata_4(m_axis_tdata_4),
    .m_axis_tkeep_4(m_axis_tkeep_4),
    .m_axis_tlast_4(m_axis_tlast_4),
    .m_axis_tvalid_4(m_axis_tvalid_4),
    .m_axis_tuser_packet_length_4(m_axis_tuser_packet_length_4),
    .m_axis_tuser_in_port_4(m_axis_tuser_in_port_4),
    .m_axis_tuser_out_port_4(m_axis_tuser_out_port_4),
    .m_axis_tuser_in_vport_4(m_axis_tuser_in_vport_4),
    .m_axis_tuser_out_vport_4(m_axis_tuser_out_vport_4),
    .m_axis_tready_4(m_axis_tready_4)
);

assign s_axi_stats_awready = 1'b0;
assign s_axi_stats_wready = 1'b0;
assign s_axi_stats_bvalid = 1'b0;
assign s_axi_stats_bresp = 2'b00;

endmodule
