# loader conflicts with test of create()
CONFIG_SKADI_LOADER=n
# APB timer also conflicts with create()
CONFIG_PULP_APB_TIMER=n
# capability for debug module also conflicts with create()
CONFIG_SKADI_DEBUG_MODULE_DRIVER=n
CONFIG_IRQ_OFFLOAD=y
CONFIG_TEST=y
CONFIG_TIMING_FUNCTIONS=y
# yes please!
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_REQUIRES_FLOAT_PRINTF=y
