# General config
CONFIG_REQUIRES_FULL_LIBC=y

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y

# Network driver config
CONFIG_TEST_RANDOM_GENERATOR=y

# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"

# Networking tweaks
# Required to handle large number of consecutive connections,
# e.g. when testing with ApacheBench.
CONFIG_NET_TCP_TIME_WAIT_DELAY=0

# Network debug config
CONFIG_NET_LOG=y
#CONFIG_NET_SHELL=y

# Skadi-specific configs
CONFIG_SKADI_SUBSYSTEM_PROVIDES_MAIN=y
CONFIG_SKADI_LIBRARY_PRINTF_STRING_BYTES_OUT_SUPPORT=y
# TODO size optimizations are broken here?
CONFIG_SPEED_OPTIMIZATIONS=y

# size optimizations
CONFIG_SKADI_SUBSYSTEM_STACK_SIZE=4095
CONFIG_SKADI_SUBSYSTEM_CALLER_TRAMPOLINE_NUM_REGISTER_SETS=16
CONFIG_SKADI_SUBSYSTEM_CALLEE_TRAMPOLINE_NUM_STACKS=16
CONFIG_SKADI_ISR_STACK_SIZE=1024
CONFIG_SKADI_LIBC_INLINE=n
CONFIG_SKADI_TEXT_ALIGN_12_BIT=n
CONFIG_SKADI_LIBRARY_LOCAL_ALLOCATOR=n
CONFIG_SKADI_LIBRARY_LOCAL_CLOCK=n
CONFIG_SKADI_EARLYCON=n
CONFIG_SKADI_SUBSYS_SYNC_ATOMIC=y

# TODO not sure why, but have encountered strange crashes with this missing
CONFIG_SKADI_COUNT_SUBSYSTEM_CALLS=y
CONFIG_SKADI_COUNT_SUBSYSTEM_CALL_ALLOC_ITERATIONS=y
