`ifndef AXIS5_ASSIGN_H
`define AXIS5_ASSIGN_H

`define AXIS5_ASSIGN(ASSIGN_OR_BLANK, TARGET_INTERFACE, ASSIGN_OP, SOURCE_INTERFACE)        \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tvalid     ASSIGN_OP SOURCE_INTERFACE.tvalid;          \
    ASSIGN_OR_BLANK SOURCE_INTERFACE.tready     ASSIGN_OP TARGET_INTERFACE.tready;          \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tdata      ASSIGN_OP SOURCE_INTERFACE.tdata;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tstrb      ASSIGN_OP SOURCE_INTERFACE.tstrb;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tkeep      ASSIGN_OP SOURCE_INTERFACE.tkeep;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tlast      ASSIGN_OP SOURCE_INTERFACE.tlast;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tid        ASSIGN_OP SOURCE_INTERFACE.tid;             \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tdest      ASSIGN_OP SOURCE_INTERFACE.tdest;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.tuser      ASSIGN_OP SOURCE_INTERFACE.tuser;           \
    ASSIGN_OR_BLANK TARGET_INTERFACE.twakeup    ASSIGN_OP SOURCE_INTERFACE.twakeup

`endif
