/**
 * AXI-Lite Register interface with a variable number of registers.
 * Data written to registers and data to be read from the registers is provided via module inputs/outputs.
 * Auto-generated by vivado 2023.2
 */

import axi5::*;
import northcape_types::*;

module northcape_reg_interface #(
    // Users to add parameters here

    // User parameters ends
    // Do not modify the parameters beyond this line

    // Width of S_AXI data bus
    parameter integer AXI_DATA_WIDTH = -1,
    // Width of S_AXI address bus
    parameter integer AXI_ADDR_WIDTH = -1,
    // number of registers
    parameter integer NUM_REGS = -1
) (
    NorthcapeRegInterfaceIO.REG_INTERFACE reg_intf,
    Axi5Lite.TO s_axi
);
  `include "axi5_functional_coverage.svh"
  `include "northcape_unread.vh"

  `AXI5_LITE_TEST_DECLARE_COVERAGE_GROUP(s_axi);

  always @(posedge (s_axi.clk_i)) begin
    `AXI5_LITE_TEST_SAMPLE_COVERAGE_GROUP(s_axi);
  end

  // AXI4LITE signals
  logic [AXI_ADDR_WIDTH-1 : 0] axi_awaddr, last_axi_awaddr;
  logic axi_awready;
  logic axi_wready;
  axi_resp_t axi_bresp;
  logic axi_bvalid;
  logic [AXI_ADDR_WIDTH-1 : 0] axi_araddr;
  logic axi_arready;
  logic [AXI_DATA_WIDTH-1 : 0] axi_rdata;
  axi_resp_t axi_rresp;
  logic axi_rvalid;

  // Example-specific design signals
  // local parameter for addressing 32 bit / 64 bit AXI_DATA_WIDTH
  // ADDR_LSB is used for addressing 32/64 bit registers/memories
  // ADDR_LSB = 2 for 32 bits (n downto 2)
  // ADDR_LSB = 3 for 64 bits (n downto 3)
  localparam integer ADDR_LSB = (AXI_DATA_WIDTH / 32) + 1;
  // account for one extra bit if not power-of-two --> would otherwise round down
  localparam integer OPT_MEM_ADDR_BITS = $clog2(
      NUM_REGS
  ) - (NUM_REGS == (1 << $clog2(
      NUM_REGS
  )) ? 1 : 0);
  //----------------------------------------------
  //-- Signals for user logic register space example
  //------------------------------------------------

  logic slv_reg_rden;
  logic slv_reg_wren;
  logic [AXI_DATA_WIDTH-1:0] reg_data_out;
  integer byte_index;
  reg aw_en;

  // I/O Connections assignments

  assign s_axi.awready = axi_awready;
  assign s_axi.wready  = axi_wready;
  assign s_axi.bresp   = axi_bresp;
  assign s_axi.bvalid  = axi_bvalid;
  assign s_axi.arready = axi_arready;
  assign s_axi.rdata   = axi_rdata;
  assign s_axi.rresp   = axi_rresp;
  assign s_axi.rvalid  = axi_rvalid;
  // Implement axi_awready generation
  // axi_awready is asserted for one s_axi.clk_i clock cycle when both
  // s_axi.awvalid and s_axi.wvalid are asserted. axi_awready is
  // de-asserted when reset is low.

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_awready <= 1'b0;
      aw_en <= 1'b1;
    end else begin
      if (~axi_awready && s_axi.awvalid && aw_en) begin
        // slave is ready to accept write address when 
        // there is a valid write address and write data
        // on the write address and data bus. This design 
        // expects no outstanding transactions. 
        axi_awready <= 1'b1;
        aw_en <= 1'b0;
      end else if (s_axi.bready && axi_bvalid) begin
        aw_en <= 1'b1;
        axi_awready <= 1'b0;
      end else begin
        axi_awready <= 1'b0;
      end
    end
  end

  // Implement axi_awaddr latching
  // This process is used to latch the address when 
  // s_axi.awvalid is valid. 

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_awaddr <= 0;
    end else begin
      if (~axi_awready && s_axi.awvalid && aw_en) begin
        // Write Address latching 
        axi_awaddr <= s_axi.awaddr;
      end
    end
  end

  // Implement axi_wready generation
  // axi_wready is asserted for one s_axi.clk_i clock cycle when both
  // s_axi.awvalid and s_axi.wvalid are asserted. axi_wready is 
  // de-asserted when reset is low. 

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_wready <= 1'b0;
    end else begin
      if (~axi_wready && s_axi.wvalid) begin
        // slave is ready to accept write data when 
        // there is a valid write address and write data
        // on the write address and data bus. This design 
        // expects no outstanding transactions. 
        axi_wready <= 1'b1;
      end else begin
        axi_wready <= 1'b0;
      end
    end
  end

  // Implement memory mapped register select and write logic generation
  // The write data is accepted and written to memory mapped registers when
  // axi_awready, s_axi.wvalid, axi_wready and s_axi.wvalid are asserted. Write strobes are used to
  // select byte enables of slave registers while writing.
  // These registers are cleared when reset (active low) is applied.
  // Slave register write enable is asserted when valid address and data are available
  // and the slave is ready to accept the write address and write data.
  assign slv_reg_wren = axi_wready && s_axi.wvalid;

  logic [OPT_MEM_ADDR_BITS:0] register_index_write;
  assign register_index_write = axi_awaddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB];

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      for (integer i = 0; i < NUM_REGS; i = i + 1) begin
        reg_intf.regs_out[i] <= '0;
      end
    end else begin
      if (slv_reg_wren) begin
        if (register_index_write < NUM_REGS) begin
          for (byte_index = 0; byte_index <= (AXI_DATA_WIDTH / 8) - 1; byte_index = byte_index + 1)
          if (s_axi.wstrb[byte_index] == 1) begin
            // Respective byte enables are asserted as per write strobes 
            // Slave register 0
            reg_intf.regs_out[register_index_write][(byte_index*8) +: 8] <= s_axi.wdata[(byte_index*8) +: 8];
          end
        end else begin
          reg_intf.regs_out <= reg_intf.regs_in;
        end
      end else begin
        // our wrapper can update what the AXI-Lite Master will read
        reg_intf.regs_out <= reg_intf.regs_in;
      end
    end
  end

  // Implement write response logic generation
  // The write response and response valid signals are asserted by the slave 
  // when axi_wready, s_axi.wvalid, axi_wready and s_axi.wvalid are asserted.  
  // This marks the acceptance of address and indicates the status of 
  // write transaction.

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_bvalid <= 0;
      axi_bresp  <= OKAY;
    end else begin
      if (~axi_bvalid && axi_wready && s_axi.wvalid) begin
        // indicates a valid write response is available
        axi_bvalid <= 1'b1;
        axi_bresp  <= OKAY;  // 'OKAY' response 
      end                   // work error responses in future
	      else
	        begin
        if (s_axi.bready && axi_bvalid) 
	            //check if bready is asserted while bvalid is high) 
	            //(there is a possibility that bready is always asserted high)   
	            begin
          axi_bvalid <= 1'b0;
        end
      end
    end
  end

  // Implement axi_arready generation
  // axi_arready is asserted for one s_axi.clk_i clock cycle when
  // s_axi.arvalid is asserted. axi_awready is 
  // de-asserted when reset (active low) is asserted. 
  // The read address is also latched when s_axi.arvalid is 
  // asserted. axi_araddr is reset to zero on reset assertion.

  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_arready <= 1'b0;
      axi_araddr  <= 0;
    end else begin
      if (~axi_arready && s_axi.arvalid) begin
        // indicates that the slave has acceped the valid read address
        axi_arready <= 1'b1;
        // Read address latching
        axi_araddr  <= s_axi.araddr;
      end else begin
        axi_arready <= 1'b0;
      end
    end
  end

  // Implement axi_arvalid generation
  // axi_rvalid is asserted for one s_axi.clk_i clock cycle when both 
  // s_axi.arvalid and axi_arready are asserted. The slave registers 
  // data are available on the axi_rdata bus at this instance. The 
  // assertion of axi_rvalid marks the validity of read data on the 
  // bus and axi_rresp indicates the status of read transaction.axi_rvalid 
  // is deasserted on reset (active low). axi_rresp and axi_rdata are 
  // cleared to zero on reset (active low).  
  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_rvalid <= 0;
      axi_rresp  <= OKAY;
    end else begin
      if (axi_arready && s_axi.arvalid && ~axi_rvalid) begin
        // Valid read data is available at the read data bus
        axi_rvalid <= 1'b1;
        axi_rresp  <= OKAY;  // 'OKAY' response
      end else if (axi_rvalid && s_axi.rready) begin
        // Read data is accepted by the master
        axi_rvalid <= 1'b0;
      end
    end
  end


  logic [OPT_MEM_ADDR_BITS:0] register_index_read;
  assign register_index_read = axi_araddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB];

  // Implement memory mapped register select and read logic generation
  // Slave register read enable is asserted when valid address is available
  // and the slave is ready to accept the read address.
  assign slv_reg_rden = axi_arready & s_axi.arvalid & ~axi_rvalid;
  always @(*) begin
    if (register_index_read < NUM_REGS) begin
      reg_data_out = reg_intf.regs_in[register_index_read];
    end else begin
      reg_data_out = 0;
    end
  end

  // Output register or memory read data
  always @(posedge s_axi.clk_i) begin
    if (s_axi.rst_ni == 1'b0) begin
      axi_rdata <= 0;
    end else begin
      // When there is a valid read address (s_axi.arvalid) with 
      // acceptance of read address by the slave (axi_arready), 
      // output the read dada 
      if (slv_reg_rden) begin
        axi_rdata <= reg_data_out;  // register read data
      end
    end
  end

  `NORTHCAPE_UNREAD(s_axi.arprot);
  `NORTHCAPE_UNREAD(s_axi.awprot);
  `NORTHCAPE_UNREAD(reg_intf.clk_i);

endmodule
