CONFIG_SKADI_SUBSYSTEM_PROVIDES_MAIN=y
CONFIG_SKADI_LIBC_SUPPORTS_FPU=y
# do not interfere please
CONFIG_NETWORKING=n
# printing in Skadi
CONFIG_SKADI_LIBRARY_PRINTF_STRING_BYTES_OUT_SUPPORT=y
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_REQUIRES_FLOAT_PRINTF=y
CONFIG_SKADI_COUNT_SUBSYSTEM_CALLS=y
# account for eval
CONFIG_ISR_STACK_SIZE=16384
