cafile ./scripts/skadi/mosquitto-ca/ca.crt
certfile ./scripts/skadi/mosquitto-ca/server.crt
dhparamfile ./scripts/skadi/mosquitto-ca/dhparam.pem
keyfile ./scripts/skadi/mosquitto-ca/server.key

password_file ./scripts/skadi/mosquitto-ca/mosquitto.pwd

port 8883
